import AdminLayout from './(panel)/AdminLayout';
import './globals.css'
import RootStyleRegistry from './mantineProvider'
import { Nunito } from "next/font/google";
const nunito = Nunito({
  weight: ["400", "700", "300", "900"],
  subsets: ["latin", "latin-ext"],
});
export const metadata = {
  title: 'Next workout',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className} suppressHydrationWarning={true}>
        <RootStyleRegistry>
          <AdminLayout>
            {children}
          </AdminLayout>
        </RootStyleRegistry>
      </body>
    </html>
  )
}
